Repository Mittelbots/Mittelbot, pull requests merged in 2023-08, with the labels that each got.

#1625 hotfix
  package-lock.json
  package.json
  src/assets/js/sessionID.js
Labels: size/XS

#1611 refactor: messageUpdate moved function
  .gitignore
  bot/events/messageUpdate.js
Labels: size/M

#1633 BETA VERSION 0.65.19
  .gitignore
  bot/events/messageCreate.js
  bot/events/messageUpdate.js
  package-lock.json
  package.json
Labels: size/M

#1638 BETA VERSION 0.65.20
  bot/events/guildCreate.js
  bot/events/interactionCreate.js
  package-lock.json
  package.json
  src/assets/js/sessionID.js
  src/slash_commands/admin/antispam.js
  src/slash_commands/admin/warnroles.js
  utils/classes/Banappeal.js
  utils/classes/Logs.js
  utils/classes/Notifications/Notifications.js
  utils/classes/Notifications/YouTube/YouTubeLogic.js
  utils/classes/Notifications/YouTube/YouTubeNotification.js
  utils/classes/Reddit.js
  utils/classes/Tickets/TicketInteraction.js
  utils/classes/Tickets/TicketsSettings.js
  utils/classes/levelsystemAPI.js
  utils/functions/modlog/modlog.js
  utils/functions/roles/giveAllRoles.js
Labels: size/M

#1644 feat: change playing status to custom status
  src/assets/json/_config/activity_dev.json
  utils/functions/activity.js
Labels: size/XS

#1645 BETA VERSION 0.65.21
  package-lock.json
  package.json
  src/assets/js/sessionID.js
  src/assets/json/_config/activity_dev.json
  src/slash_commands/fun/hangman.js
  utils/classes/Reddit.js
  utils/functions/activity.js
Labels: size/S

#1646 feat: hasPermission unit test & automatic tests in pipeline
  .github/workflows/tests.yml
  package-lock.json
  package.json
  tests/unit/src/db/db.test.js
  tests/unit/utils/function/createSlashCommands/createSlashCommands.test.js
  tests/unit/utils/function/hasPermissions.test.js
  utils/functions/hasPermissions.js
Labels: size/L

#1649 feat: automatic utils function tests
  tests/integration/src/assets/js/sessionID.test.js
  tests/integration/utils/functions/getLinesOfCode/getLinesOfCode.test.js
  tests/integration/utils/functions/validate/isValidDiscordAttachmentsLink.test.js
  tests/integration/utils/functions/validate/isValidDiscordInvite.test.js
  tests/integration/utils/functions/validate/isValidHexCode.test.js
  tests/integration/utils/functions/validate/isValidLink.test.js
  tests/unit/utils/function/checkMessage/checkMessage.test.js
  utils/functions/validate/isValidHexCode.js
Labels: size/L

#1651 fix: false installation on windows
  scripts/install-windows.bat
Labels: size/M
